/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/irm/v1alpha2/incidents_service.proto

package com.google.irm.service.v1alpha2.api;

public interface CreateIncidentRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.irm.v1alpha2.CreateIncidentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * The incident to create.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident incident = 1;</code>
   *
   * @return Whether the incident field is set.
   */
  boolean hasIncident();
  /**
   *
   *
   * <pre>
   * The incident to create.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident incident = 1;</code>
   *
   * @return The incident.
   */
  com.google.irm.service.v1alpha2.api.Incident getIncident();
  /**
   *
   *
   * <pre>
   * The incident to create.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident incident = 1;</code>
   */
  com.google.irm.service.v1alpha2.api.IncidentOrBuilder getIncidentOrBuilder();

  /**
   *
   *
   * <pre>
   * The resource name of the hosting Stackdriver project which the incident
   * belongs to.
   * The name is of the form `projects/{project_id_or_number}`
   * .
   * </pre>
   *
   * <code>string parent = 2;</code>
   *
   * @return The parent.
   */
  java.lang.String getParent();
  /**
   *
   *
   * <pre>
   * The resource name of the hosting Stackdriver project which the incident
   * belongs to.
   * The name is of the form `projects/{project_id_or_number}`
   * .
   * </pre>
   *
   * <code>string parent = 2;</code>
   *
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString getParentBytes();
}
