/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/irm/v1alpha2/incidents.proto

package com.google.irm.service.v1alpha2.api;

public interface IncidentOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.irm.v1alpha2.Incident)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Output only. Resource name of the incident, for example,
   * "projects/{project_id}/incidents/{incident_id}".
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   *
   *
   * <pre>
   * Output only. Resource name of the incident, for example,
   * "projects/{project_id}/incidents/{incident_id}".
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   *
   *
   * <pre>
   * One-line summary of the incident.
   * </pre>
   *
   * <code>string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   *
   *
   * <pre>
   * One-line summary of the incident.
   * </pre>
   *
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString getTitleBytes();

  /**
   *
   *
   * <pre>
   * Escalation level of the incident.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident.EscalationLevel escalation_level = 3;</code>
   */
  int getEscalationLevelValue();
  /**
   *
   *
   * <pre>
   * Escalation level of the incident.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident.EscalationLevel escalation_level = 3;</code>
   */
  com.google.irm.service.v1alpha2.api.Incident.EscalationLevel getEscalationLevel();

  /**
   *
   *
   * <pre>
   * Etag to validate the object is unchanged for a read-modify-write operation.
   * An empty etag will overwrite other changes.
   * </pre>
   *
   * <code>string etag = 4;</code>
   */
  java.lang.String getEtag();
  /**
   *
   *
   * <pre>
   * Etag to validate the object is unchanged for a read-modify-write operation.
   * An empty etag will overwrite other changes.
   * </pre>
   *
   * <code>string etag = 4;</code>
   */
  com.google.protobuf.ByteString getEtagBytes();

  /**
   *
   *
   * <pre>
   * Severity of the incident.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident.Severity severity = 5;</code>
   */
  int getSeverityValue();
  /**
   *
   *
   * <pre>
   * Severity of the incident.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident.Severity severity = 5;</code>
   */
  com.google.irm.service.v1alpha2.api.Incident.Severity getSeverity();

  /**
   *
   *
   * <pre>
   * Stage of the incident.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident.Stage stage = 6;</code>
   */
  int getStageValue();
  /**
   *
   *
   * <pre>
   * Stage of the incident.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident.Stage stage = 6;</code>
   */
  com.google.irm.service.v1alpha2.api.Incident.Stage getStage();

  /**
   *
   *
   * <pre>
   * Resource name of the incident this incident is a duplicate of. Empty if
   * this incident is not a duplicate.
   * An incident can only be a duplicate of an incident that is not marked as a
   * duplicate already. Setting this to a non-empty value must also set the
   * stage to `STAGE_DUPLICATE`. Unsetting this value value must also update
   * `stage` to a value other than `STAGE_DUPLICATE`.
   * </pre>
   *
   * <code>string duplicate_incident = 9;</code>
   */
  java.lang.String getDuplicateIncident();
  /**
   *
   *
   * <pre>
   * Resource name of the incident this incident is a duplicate of. Empty if
   * this incident is not a duplicate.
   * An incident can only be a duplicate of an incident that is not marked as a
   * duplicate already. Setting this to a non-empty value must also set the
   * stage to `STAGE_DUPLICATE`. Unsetting this value value must also update
   * `stage` to a value other than `STAGE_DUPLICATE`.
   * </pre>
   *
   * <code>string duplicate_incident = 9;</code>
   */
  com.google.protobuf.ByteString getDuplicateIncidentBytes();

  /**
   *
   *
   * <pre>
   * Output only. Time this incident started. Used to measure the 'elapsed
   * time'. Start time of an incident is the earliest creation time of any of
   * its Signals or the create time of the incident if no Signals are assigned.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 7;</code>
   */
  boolean hasStartTime();
  /**
   *
   *
   * <pre>
   * Output only. Time this incident started. Used to measure the 'elapsed
   * time'. Start time of an incident is the earliest creation time of any of
   * its Signals or the create time of the incident if no Signals are assigned.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 7;</code>
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   *
   *
   * <pre>
   * Output only. Time this incident started. Used to measure the 'elapsed
   * time'. Start time of an incident is the earliest creation time of any of
   * its Signals or the create time of the incident if no Signals are assigned.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   *
   *
   * <pre>
   * Output only. Synopsis of this incident.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Synopsis synopsis = 8;</code>
   */
  boolean hasSynopsis();
  /**
   *
   *
   * <pre>
   * Output only. Synopsis of this incident.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Synopsis synopsis = 8;</code>
   */
  com.google.irm.service.v1alpha2.api.Synopsis getSynopsis();
  /**
   *
   *
   * <pre>
   * Output only. Synopsis of this incident.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Synopsis synopsis = 8;</code>
   */
  com.google.irm.service.v1alpha2.api.SynopsisOrBuilder getSynopsisOrBuilder();

  /**
   *
   *
   * <pre>
   * Location of communications for this incident. This is informational
   * only; IRM does not use this to send messages.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident.CommunicationVenue communication_venue = 10;</code>
   */
  boolean hasCommunicationVenue();
  /**
   *
   *
   * <pre>
   * Location of communications for this incident. This is informational
   * only; IRM does not use this to send messages.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident.CommunicationVenue communication_venue = 10;</code>
   */
  com.google.irm.service.v1alpha2.api.Incident.CommunicationVenue getCommunicationVenue();
  /**
   *
   *
   * <pre>
   * Location of communications for this incident. This is informational
   * only; IRM does not use this to send messages.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.Incident.CommunicationVenue communication_venue = 10;</code>
   */
  com.google.irm.service.v1alpha2.api.Incident.CommunicationVenueOrBuilder
      getCommunicationVenueOrBuilder();
}
