/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/irm/v1alpha2/incidents.proto

package com.google.irm.service.v1alpha2.api;

public final class Incidents {
  private Incidents() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_User_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_Signal_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_Signal_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_Signal_SignalArtifact_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_Signal_SignalArtifact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_Annotation_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_Annotation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_Tag_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_Tag_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_Synopsis_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_Synopsis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_Incident_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_Incident_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_Incident_CommunicationVenue_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_Incident_CommunicationVenue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_IncidentRole_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_IncidentRole_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_IncidentRoleAssignment_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_IncidentRoleAssignment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_Artifact_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_Artifact_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_Email_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_Email_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_NotificationChannel_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_NotificationChannel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_irm_v1alpha2_Subscription_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_irm_v1alpha2_Subscription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n)google/cloud/irm/v1alpha2/incidents.pr"
          + "oto\022\031google.cloud.irm.v1alpha2\032\034google/a"
          + "pi/annotations.proto\032\037google/protobuf/ti"
          + "mestamp.proto\"2\n\004User\022\021\n\007user_id\030\001 \001(\tH\000"
          + "\022\017\n\005email\030\002 \001(\tH\000B\006\n\004user\"\302\004\n\006Signal\022\014\n\004"
          + "name\030\001 \001(\t\022\014\n\004etag\030\002 \001(\t\022\020\n\010incident\030\003 \001"
          + "(\t\022/\n\013create_time\030\004 \001(\0132\032.google.protobu"
          + "f.Timestamp\022.\n\nclose_time\030\n \001(\0132\032.google"
          + ".protobuf.Timestamp\022/\n\013detect_time\030\017 \001(\013"
          + "2\032.google.protobuf.Timestamp\0220\n\007creator\030"
          + "\005 \001(\0132\037.google.cloud.irm.v1alpha2.User\022\r"
          + "\n\005title\030\006 \001(\t\022\024\n\014content_type\030\007 \001(\t\022\017\n\007c"
          + "ontent\030\010 \001(\t\022=\n\014signal_state\030\t \001(\0162\'.goo"
          + "gle.cloud.irm.v1alpha2.Signal.State\022J\n\020s"
          + "ignal_artifacts\030\020 \003(\01320.google.cloud.irm"
          + ".v1alpha2.Signal.SignalArtifact\032C\n\016Signa"
          + "lArtifact\022\023\n\tuser_type\030\002 \001(\tH\000\022\013\n\003uri\030\003 "
          + "\001(\tB\017\n\rartifact_type\"@\n\005State\022\025\n\021STATE_U"
          + "NSPECIFIED\020\000\022\016\n\nSTATE_OPEN\020\001\022\020\n\014STATE_CL"
          + "OSED\020\002\"\243\001\n\nAnnotation\022\014\n\004name\030\001 \001(\t\022/\n\006a"
          + "uthor\030\002 \001(\0132\037.google.cloud.irm.v1alpha2."
          + "User\022/\n\013create_time\030\003 \001(\0132\032.google.proto"
          + "buf.Timestamp\022\017\n\007content\030\004 \001(\t\022\024\n\014conten"
          + "t_type\030\005 \001(\t\")\n\003Tag\022\014\n\004name\030\001 \001(\t\022\024\n\014dis"
          + "play_name\030\002 \001(\t\"\223\001\n\010Synopsis\022\024\n\014content_"
          + "type\030\001 \001(\t\022\017\n\007content\030\002 \001(\t\022/\n\013update_ti"
          + "me\030\003 \001(\0132\032.google.protobuf.Timestamp\022/\n\006"
          + "author\030\004 \001(\0132\037.google.cloud.irm.v1alpha2"
          + ".User\"\311\010\n\010Incident\022\014\n\004name\030\001 \001(\t\022\r\n\005titl"
          + "e\030\002 \001(\t\022M\n\020escalation_level\030\003 \001(\01623.goog"
          + "le.cloud.irm.v1alpha2.Incident.Escalatio"
          + "nLevel\022\014\n\004etag\030\004 \001(\t\022>\n\010severity\030\005 \001(\0162,"
          + ".google.cloud.irm.v1alpha2.Incident.Seve"
          + "rity\0228\n\005stage\030\006 \001(\0162).google.cloud.irm.v"
          + "1alpha2.Incident.Stage\022\032\n\022duplicate_inci"
          + "dent\030\t \001(\t\022.\n\nstart_time\030\007 \001(\0132\032.google."
          + "protobuf.Timestamp\0225\n\010synopsis\030\010 \001(\0132#.g"
          + "oogle.cloud.irm.v1alpha2.Synopsis\022S\n\023com"
          + "munication_venue\030\n \001(\01326.google.cloud.ir"
          + "m.v1alpha2.Incident.CommunicationVenue\032\354"
          + "\001\n\022CommunicationVenue\022\013\n\003uri\030\001 \001(\t\022\024\n\014di"
          + "splay_name\030\002 \001(\t\022X\n\014channel_type\030\003 \001(\0162B"
          + ".google.cloud.irm.v1alpha2.Incident.Comm"
          + "unicationVenue.ChannelType\"Y\n\013ChannelTyp"
          + "e\022\034\n\030CHANNEL_TYPE_UNSPECIFIED\020\000\022\024\n\020CHANN"
          + "EL_TYPE_URI\020\001\022\026\n\022CHANNEL_TYPE_SLACK\020\005\"V\n"
          + "\017EscalationLevel\022 \n\034ESCALATION_LEVEL_UNS"
          + "PECIFIED\020\000\022!\n\035ESCALATION_LEVEL_ORGANIZAT"
          + "ION\020\001\"\215\001\n\010Severity\022\030\n\024SEVERITY_UNSPECIFI"
          + "ED\020\000\022\021\n\rSEVERITY_HUGE\020\001\022\022\n\016SEVERITY_MAJO"
          + "R\020\002\022\023\n\017SEVERITY_MEDIUM\020\003\022\022\n\016SEVERITY_MIN"
          + "OR\020\004\022\027\n\023SEVERITY_NEGLIGIBLE\020\005\"\231\001\n\005Stage\022"
          + "\025\n\021STAGE_UNSPECIFIED\020\000\022\022\n\016STAGE_DETECTED"
          + "\020\004\022\021\n\rSTAGE_TRIAGED\020\001\022\023\n\017STAGE_MITIGATED"
          + "\020\002\022\022\n\016STAGE_RESOLVED\020\003\022\024\n\020STAGE_DOCUMENT"
          + "ED\020\005\022\023\n\017STAGE_DUPLICATE\020\006\"\326\002\n\014IncidentRo"
          + "le\022:\n\004type\030\001 \001(\0162,.google.cloud.irm.v1al"
          + "pha2.IncidentRole.Type\022\r\n\005title\030\002 \001(\t\022\023\n"
          + "\013description\030\003 \001(\t\"\345\001\n\004Type\022\024\n\020TYPE_UNSP"
          + "ECIFIED\020\000\022\033\n\027TYPE_INCIDENT_COMMANDER\020\001\022\034"
          + "\n\030TYPE_COMMUNICATIONS_LEAD\020\002\022\030\n\024TYPE_OPE"
          + "RATIONS_LEAD\020\003\022.\n*TYPE_EXTERNAL_CUSTOMER"
          + "_COMMUNICATIONS_LEAD\020\004\022\027\n\023TYPE_PRIMARY_O"
          + "NCALL\020\005\022\031\n\025TYPE_SECONDARY_ONCALL\020\006\022\016\n\nTY"
          + "PE_OTHER\020\007\"\332\001\n\026IncidentRoleAssignment\022\014\n"
          + "\004name\030\001 \001(\t\022\014\n\004etag\030\002 \001(\t\0225\n\004role\030\003 \001(\0132"
          + "\'.google.cloud.irm.v1alpha2.IncidentRole"
          + "\0221\n\010assignee\030\004 \001(\0132\037.google.cloud.irm.v1"
          + "alpha2.User\022:\n\021proposed_assignee\030\005 \001(\0132\037"
          + ".google.cloud.irm.v1alpha2.User\"\302\001\n\010Arti"
          + "fact\022\014\n\004name\030\001 \001(\t\022\024\n\014display_name\030\002 \001(\t"
          + "\022\014\n\004etag\030\003 \001(\t\022\013\n\003url\030\004 \001(\t\0226\n\004type\030\005 \001("
          + "\0162(.google.cloud.irm.v1alpha2.Artifact.T"
          + "ype\"?\n\004Type\022\024\n\020TYPE_UNSPECIFIED\020\000\022\014\n\010TYP"
          + "E_URL\020\001\022\023\n\017TYPE_JIRA_ISSUE\020\004\"\216\002\n\024Communi"
          + "cationChannel\022F\n\005email\030\001 \001(\01325.google.cl"
          + "oud.irm.v1alpha2.CommunicationChannel.Em"
          + "ailH\000\022c\n\024notification_channel\030\002 \001(\0132C.go"
          + "ogle.cloud.irm.v1alpha2.CommunicationCha"
          + "nnel.NotificationChannelH\000\032\030\n\005Email\022\017\n\007a"
          + "ddress\030\001 \001(\t\032#\n\023NotificationChannel\022\014\n\004n"
          + "ame\030\001 \001(\tB\n\n\010endpoint\"\246\003\n\014Subscription\022\014"
          + "\n\004name\030\001 \001(\t\022\014\n\004etag\030\002 \001(\t\022M\n\024subscripti"
          + "on_channel\030\003 \001(\0132/.google.cloud.irm.v1al"
          + "pha2.CommunicationChannel\022F\n\013event_types"
          + "\030\004 \003(\01621.google.cloud.irm.v1alpha2.Subsc"
          + "ription.EventType\"\342\001\n\tEventType\022\032\n\026EVENT"
          + "_TYPE_UNSPECIFIED\020\000\022\033\n\027EVENT_TYPE_TITLE_"
          + "CHANGE\020\001\022\036\n\032EVENT_TYPE_SYNOPSIS_CHANGE\020\002"
          + "\022\033\n\027EVENT_TYPE_STAGE_CHANGE\020\003\022\036\n\032EVENT_T"
          + "YPE_SEVERITY_CHANGE\020\004\022\035\n\031EVENT_TYPE_ANNO"
          + "TATION_ADD\020\005\022 \n\034EVENT_TYPE_ANNOTATION_CH"
          + "ANGE\020\006Bh\n#com.google.irm.service.v1alpha"
          + "2.apiP\001Z<google.golang.org/genproto/goog"
          + "leapis/cloud/irm/v1alpha2;irm\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        },
        assigner);
    internal_static_google_cloud_irm_v1alpha2_User_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_irm_v1alpha2_User_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_User_descriptor,
            new java.lang.String[] {
              "UserId", "Email", "User",
            });
    internal_static_google_cloud_irm_v1alpha2_Signal_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_irm_v1alpha2_Signal_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_Signal_descriptor,
            new java.lang.String[] {
              "Name",
              "Etag",
              "Incident",
              "CreateTime",
              "CloseTime",
              "DetectTime",
              "Creator",
              "Title",
              "ContentType",
              "Content",
              "SignalState",
              "SignalArtifacts",
            });
    internal_static_google_cloud_irm_v1alpha2_Signal_SignalArtifact_descriptor =
        internal_static_google_cloud_irm_v1alpha2_Signal_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_irm_v1alpha2_Signal_SignalArtifact_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_Signal_SignalArtifact_descriptor,
            new java.lang.String[] {
              "UserType", "Uri", "ArtifactType",
            });
    internal_static_google_cloud_irm_v1alpha2_Annotation_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_irm_v1alpha2_Annotation_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_Annotation_descriptor,
            new java.lang.String[] {
              "Name", "Author", "CreateTime", "Content", "ContentType",
            });
    internal_static_google_cloud_irm_v1alpha2_Tag_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_irm_v1alpha2_Tag_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_Tag_descriptor,
            new java.lang.String[] {
              "Name", "DisplayName",
            });
    internal_static_google_cloud_irm_v1alpha2_Synopsis_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_irm_v1alpha2_Synopsis_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_Synopsis_descriptor,
            new java.lang.String[] {
              "ContentType", "Content", "UpdateTime", "Author",
            });
    internal_static_google_cloud_irm_v1alpha2_Incident_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_irm_v1alpha2_Incident_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_Incident_descriptor,
            new java.lang.String[] {
              "Name",
              "Title",
              "EscalationLevel",
              "Etag",
              "Severity",
              "Stage",
              "DuplicateIncident",
              "StartTime",
              "Synopsis",
              "CommunicationVenue",
            });
    internal_static_google_cloud_irm_v1alpha2_Incident_CommunicationVenue_descriptor =
        internal_static_google_cloud_irm_v1alpha2_Incident_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_irm_v1alpha2_Incident_CommunicationVenue_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_Incident_CommunicationVenue_descriptor,
            new java.lang.String[] {
              "Uri", "DisplayName", "ChannelType",
            });
    internal_static_google_cloud_irm_v1alpha2_IncidentRole_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_irm_v1alpha2_IncidentRole_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_IncidentRole_descriptor,
            new java.lang.String[] {
              "Type", "Title", "Description",
            });
    internal_static_google_cloud_irm_v1alpha2_IncidentRoleAssignment_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_irm_v1alpha2_IncidentRoleAssignment_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_IncidentRoleAssignment_descriptor,
            new java.lang.String[] {
              "Name", "Etag", "Role", "Assignee", "ProposedAssignee",
            });
    internal_static_google_cloud_irm_v1alpha2_Artifact_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_irm_v1alpha2_Artifact_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_Artifact_descriptor,
            new java.lang.String[] {
              "Name", "DisplayName", "Etag", "Url", "Type",
            });
    internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_descriptor,
            new java.lang.String[] {
              "Email", "NotificationChannel", "Endpoint",
            });
    internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_Email_descriptor =
        internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_Email_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_Email_descriptor,
            new java.lang.String[] {
              "Address",
            });
    internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_NotificationChannel_descriptor =
        internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_NotificationChannel_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_CommunicationChannel_NotificationChannel_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_irm_v1alpha2_Subscription_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_irm_v1alpha2_Subscription_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_irm_v1alpha2_Subscription_descriptor,
            new java.lang.String[] {
              "Name", "Etag", "SubscriptionChannel", "EventTypes",
            });
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
