/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/irm/v1alpha2/incidents_service.proto

package com.google.irm.service.v1alpha2.api;

/**
 *
 *
 * <pre>
 * SendShiftHandoff and PreviewShiftHandoff RPC request.
 * </pre>
 *
 * Protobuf type {@code google.cloud.irm.v1alpha2.SendShiftHandoffRequest}
 */
public final class SendShiftHandoffRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.cloud.irm.v1alpha2.SendShiftHandoffRequest)
    SendShiftHandoffRequestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use SendShiftHandoffRequest.newBuilder() to construct.
  private SendShiftHandoffRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private SendShiftHandoffRequest() {
    parent_ = "";
    recipients_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    cc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    subject_ = "";
    notesContentType_ = "";
    notesContent_ = "";
    incidents_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private SendShiftHandoffRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              java.lang.String s = input.readStringRequireUtf8();

              parent_ = s;
              break;
            }
          case 18:
            {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                recipients_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              recipients_.add(s);
              break;
            }
          case 26:
            {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                cc_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              cc_.add(s);
              break;
            }
          case 34:
            {
              java.lang.String s = input.readStringRequireUtf8();

              subject_ = s;
              break;
            }
          case 42:
            {
              java.lang.String s = input.readStringRequireUtf8();

              notesContentType_ = s;
              break;
            }
          case 50:
            {
              java.lang.String s = input.readStringRequireUtf8();

              notesContent_ = s;
              break;
            }
          case 58:
            {
              if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                incidents_ =
                    new java.util.ArrayList<
                        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident>();
                mutable_bitField0_ |= 0x00000040;
              }
              incidents_.add(
                  input.readMessage(
                      com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.parser(),
                      extensionRegistry));
              break;
            }
          case 64:
            {
              previewOnly_ = input.readBool();
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        recipients_ = recipients_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        cc_ = cc_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000040) != 0)) {
        incidents_ = java.util.Collections.unmodifiableList(incidents_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.irm.service.v1alpha2.api.IncidentsService
        .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.irm.service.v1alpha2.api.IncidentsService
        .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.class,
            com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Builder.class);
  }

  public interface IncidentOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident)
      com.google.protobuf.MessageOrBuilder {

    /**
     *
     *
     * <pre>
     * Resource name of the incident, for example,
     * "projects/{project_id}/incidents/{incident_id}".
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     *
     *
     * <pre>
     * Resource name of the incident, for example,
     * "projects/{project_id}/incidents/{incident_id}".
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString getNameBytes();
  }
  /**
   *
   *
   * <pre>
   * Describes an incident for inclusion in the handoff.
   * This is wrapped in a message to provide flexibility for potentially
   * attaching additional data to each incident in the future.
   * </pre>
   *
   * Protobuf type {@code google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident}
   */
  public static final class Incident extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident)
      IncidentOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Incident.newBuilder() to construct.
    private Incident(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Incident() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Incident(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.irm.service.v1alpha2.api.IncidentsService
          .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_Incident_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.irm.service.v1alpha2.api.IncidentsService
          .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_Incident_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.class,
              com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     *
     *
     * <pre>
     * Resource name of the incident, for example,
     * "projects/{project_id}/incidents/{incident_id}".
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     *
     *
     * <pre>
     * Resource name of the incident, for example,
     * "projects/{project_id}/incidents/{incident_id}".
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident)) {
        return super.equals(obj);
      }
      com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident other =
          (com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident) obj;

      if (!getName().equals(other.getName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
        parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     *
     *
     * <pre>
     * Describes an incident for inclusion in the handoff.
     * This is wrapped in a message to provide flexibility for potentially
     * attaching additional data to each incident in the future.
     * </pre>
     *
     * Protobuf type {@code google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident)
        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.IncidentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.google.irm.service.v1alpha2.api.IncidentsService
            .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_Incident_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.irm.service.v1alpha2.api.IncidentsService
            .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_Incident_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.class,
                com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder.class);
      }

      // Construct using
      // com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return com.google.irm.service.v1alpha2.api.IncidentsService
            .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_Incident_descriptor;
      }

      @java.lang.Override
      public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
          getDefaultInstanceForType() {
        return com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
            .getDefaultInstance();
      }

      @java.lang.Override
      public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident build() {
        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident result =
            buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident buildPartial() {
        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident result =
            new com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident) {
          return mergeFrom(
              (com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(
          com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident other) {
        if (other
            == com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
                .getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       *
       *
       * <pre>
       * Resource name of the incident, for example,
       * "projects/{project_id}/incidents/{incident_id}".
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       *
       *
       * <pre>
       * Resource name of the incident, for example,
       * "projects/{project_id}/incidents/{incident_id}".
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       *
       *
       * <pre>
       * Resource name of the incident, for example,
       * "projects/{project_id}/incidents/{incident_id}".
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       *
       *
       * <pre>
       * Resource name of the incident, for example,
       * "projects/{project_id}/incidents/{incident_id}".
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       *
       *
       * <pre>
       * Resource name of the incident, for example,
       * "projects/{project_id}/incidents/{incident_id}".
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident)
    }

    // @@protoc_insertion_point(class_scope:google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident)
    private static final com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident();
    }

    public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Incident> PARSER =
        new com.google.protobuf.AbstractParser<Incident>() {
          @java.lang.Override
          public Incident parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Incident(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<Incident> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Incident> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
        getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private int bitField0_;
  public static final int PARENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object parent_;
  /**
   *
   *
   * <pre>
   * The resource name of the Stackdriver project that the handoff is being sent
   * from. for example, `projects/{project_id}`
   * </pre>
   *
   * <code>string parent = 1;</code>
   */
  public java.lang.String getParent() {
    java.lang.Object ref = parent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parent_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * The resource name of the Stackdriver project that the handoff is being sent
   * from. for example, `projects/{project_id}`
   * </pre>
   *
   * <code>string parent = 1;</code>
   */
  public com.google.protobuf.ByteString getParentBytes() {
    java.lang.Object ref = parent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      parent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECIPIENTS_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList recipients_;
  /**
   *
   *
   * <pre>
   * Email addresses of the recipients of the handoff, for example,
   * "user&#64;example.com". Must contain at least one entry.
   * </pre>
   *
   * <code>repeated string recipients = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList getRecipientsList() {
    return recipients_;
  }
  /**
   *
   *
   * <pre>
   * Email addresses of the recipients of the handoff, for example,
   * "user&#64;example.com". Must contain at least one entry.
   * </pre>
   *
   * <code>repeated string recipients = 2;</code>
   */
  public int getRecipientsCount() {
    return recipients_.size();
  }
  /**
   *
   *
   * <pre>
   * Email addresses of the recipients of the handoff, for example,
   * "user&#64;example.com". Must contain at least one entry.
   * </pre>
   *
   * <code>repeated string recipients = 2;</code>
   */
  public java.lang.String getRecipients(int index) {
    return recipients_.get(index);
  }
  /**
   *
   *
   * <pre>
   * Email addresses of the recipients of the handoff, for example,
   * "user&#64;example.com". Must contain at least one entry.
   * </pre>
   *
   * <code>repeated string recipients = 2;</code>
   */
  public com.google.protobuf.ByteString getRecipientsBytes(int index) {
    return recipients_.getByteString(index);
  }

  public static final int CC_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList cc_;
  /**
   *
   *
   * <pre>
   * Email addresses that should be CC'd on the handoff. Optional.
   * </pre>
   *
   * <code>repeated string cc = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList getCcList() {
    return cc_;
  }
  /**
   *
   *
   * <pre>
   * Email addresses that should be CC'd on the handoff. Optional.
   * </pre>
   *
   * <code>repeated string cc = 3;</code>
   */
  public int getCcCount() {
    return cc_.size();
  }
  /**
   *
   *
   * <pre>
   * Email addresses that should be CC'd on the handoff. Optional.
   * </pre>
   *
   * <code>repeated string cc = 3;</code>
   */
  public java.lang.String getCc(int index) {
    return cc_.get(index);
  }
  /**
   *
   *
   * <pre>
   * Email addresses that should be CC'd on the handoff. Optional.
   * </pre>
   *
   * <code>repeated string cc = 3;</code>
   */
  public com.google.protobuf.ByteString getCcBytes(int index) {
    return cc_.getByteString(index);
  }

  public static final int SUBJECT_FIELD_NUMBER = 4;
  private volatile java.lang.Object subject_;
  /**
   *
   *
   * <pre>
   * The subject of the email. Required.
   * </pre>
   *
   * <code>string subject = 4;</code>
   */
  public java.lang.String getSubject() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subject_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * The subject of the email. Required.
   * </pre>
   *
   * <code>string subject = 4;</code>
   */
  public com.google.protobuf.ByteString getSubjectBytes() {
    java.lang.Object ref = subject_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      subject_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTES_CONTENT_TYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object notesContentType_;
  /**
   *
   *
   * <pre>
   * Content type string, for example, 'text/plain' or 'text/html'.
   * </pre>
   *
   * <code>string notes_content_type = 5;</code>
   */
  public java.lang.String getNotesContentType() {
    java.lang.Object ref = notesContentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notesContentType_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Content type string, for example, 'text/plain' or 'text/html'.
   * </pre>
   *
   * <code>string notes_content_type = 5;</code>
   */
  public com.google.protobuf.ByteString getNotesContentTypeBytes() {
    java.lang.Object ref = notesContentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      notesContentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOTES_CONTENT_FIELD_NUMBER = 6;
  private volatile java.lang.Object notesContent_;
  /**
   *
   *
   * <pre>
   * Additional notes to be included in the handoff. Optional.
   * </pre>
   *
   * <code>string notes_content = 6;</code>
   */
  public java.lang.String getNotesContent() {
    java.lang.Object ref = notesContent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      notesContent_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Additional notes to be included in the handoff. Optional.
   * </pre>
   *
   * <code>string notes_content = 6;</code>
   */
  public com.google.protobuf.ByteString getNotesContentBytes() {
    java.lang.Object ref = notesContent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      notesContent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INCIDENTS_FIELD_NUMBER = 7;
  private java.util.List<com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident>
      incidents_;
  /**
   *
   *
   * <pre>
   * The set of incidents that should be included in the handoff. Optional.
   * </pre>
   *
   * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
   * </code>
   */
  public java.util.List<com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident>
      getIncidentsList() {
    return incidents_;
  }
  /**
   *
   *
   * <pre>
   * The set of incidents that should be included in the handoff. Optional.
   * </pre>
   *
   * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
   * </code>
   */
  public java.util.List<
          ? extends com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.IncidentOrBuilder>
      getIncidentsOrBuilderList() {
    return incidents_;
  }
  /**
   *
   *
   * <pre>
   * The set of incidents that should be included in the handoff. Optional.
   * </pre>
   *
   * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
   * </code>
   */
  public int getIncidentsCount() {
    return incidents_.size();
  }
  /**
   *
   *
   * <pre>
   * The set of incidents that should be included in the handoff. Optional.
   * </pre>
   *
   * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
   * </code>
   */
  public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident getIncidents(
      int index) {
    return incidents_.get(index);
  }
  /**
   *
   *
   * <pre>
   * The set of incidents that should be included in the handoff. Optional.
   * </pre>
   *
   * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
   * </code>
   */
  public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.IncidentOrBuilder
      getIncidentsOrBuilder(int index) {
    return incidents_.get(index);
  }

  public static final int PREVIEW_ONLY_FIELD_NUMBER = 8;
  private boolean previewOnly_;
  /**
   *
   *
   * <pre>
   * If set to true a ShiftHandoffResponse will be returned but the handoff
   * will not actually be sent.
   * </pre>
   *
   * <code>bool preview_only = 8;</code>
   */
  public boolean getPreviewOnly() {
    return previewOnly_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getParentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, parent_);
    }
    for (int i = 0; i < recipients_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, recipients_.getRaw(i));
    }
    for (int i = 0; i < cc_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cc_.getRaw(i));
    }
    if (!getSubjectBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, subject_);
    }
    if (!getNotesContentTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, notesContentType_);
    }
    if (!getNotesContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, notesContent_);
    }
    for (int i = 0; i < incidents_.size(); i++) {
      output.writeMessage(7, incidents_.get(i));
    }
    if (previewOnly_ != false) {
      output.writeBool(8, previewOnly_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getParentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, parent_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < recipients_.size(); i++) {
        dataSize += computeStringSizeNoTag(recipients_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRecipientsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < cc_.size(); i++) {
        dataSize += computeStringSizeNoTag(cc_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getCcList().size();
    }
    if (!getSubjectBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, subject_);
    }
    if (!getNotesContentTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, notesContentType_);
    }
    if (!getNotesContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, notesContent_);
    }
    for (int i = 0; i < incidents_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(7, incidents_.get(i));
    }
    if (previewOnly_ != false) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(8, previewOnly_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest)) {
      return super.equals(obj);
    }
    com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest other =
        (com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest) obj;

    if (!getParent().equals(other.getParent())) return false;
    if (!getRecipientsList().equals(other.getRecipientsList())) return false;
    if (!getCcList().equals(other.getCcList())) return false;
    if (!getSubject().equals(other.getSubject())) return false;
    if (!getNotesContentType().equals(other.getNotesContentType())) return false;
    if (!getNotesContent().equals(other.getNotesContent())) return false;
    if (!getIncidentsList().equals(other.getIncidentsList())) return false;
    if (getPreviewOnly() != other.getPreviewOnly()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PARENT_FIELD_NUMBER;
    hash = (53 * hash) + getParent().hashCode();
    if (getRecipientsCount() > 0) {
      hash = (37 * hash) + RECIPIENTS_FIELD_NUMBER;
      hash = (53 * hash) + getRecipientsList().hashCode();
    }
    if (getCcCount() > 0) {
      hash = (37 * hash) + CC_FIELD_NUMBER;
      hash = (53 * hash) + getCcList().hashCode();
    }
    hash = (37 * hash) + SUBJECT_FIELD_NUMBER;
    hash = (53 * hash) + getSubject().hashCode();
    hash = (37 * hash) + NOTES_CONTENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getNotesContentType().hashCode();
    hash = (37 * hash) + NOTES_CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getNotesContent().hashCode();
    if (getIncidentsCount() > 0) {
      hash = (37 * hash) + INCIDENTS_FIELD_NUMBER;
      hash = (53 * hash) + getIncidentsList().hashCode();
    }
    hash = (37 * hash) + PREVIEW_ONLY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getPreviewOnly());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(
      com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * SendShiftHandoff and PreviewShiftHandoff RPC request.
   * </pre>
   *
   * Protobuf type {@code google.cloud.irm.v1alpha2.SendShiftHandoffRequest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.cloud.irm.v1alpha2.SendShiftHandoffRequest)
      com.google.irm.service.v1alpha2.api.SendShiftHandoffRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.irm.service.v1alpha2.api.IncidentsService
          .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.irm.service.v1alpha2.api.IncidentsService
          .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.class,
              com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Builder.class);
    }

    // Construct using com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        getIncidentsFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      parent_ = "";

      recipients_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      cc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      subject_ = "";

      notesContentType_ = "";

      notesContent_ = "";

      if (incidentsBuilder_ == null) {
        incidents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        incidentsBuilder_.clear();
      }
      previewOnly_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.irm.service.v1alpha2.api.IncidentsService
          .internal_static_google_cloud_irm_v1alpha2_SendShiftHandoffRequest_descriptor;
    }

    @java.lang.Override
    public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest getDefaultInstanceForType() {
      return com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest build() {
      com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest buildPartial() {
      com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest result =
          new com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.parent_ = parent_;
      if (((bitField0_ & 0x00000002) != 0)) {
        recipients_ = recipients_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.recipients_ = recipients_;
      if (((bitField0_ & 0x00000004) != 0)) {
        cc_ = cc_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.cc_ = cc_;
      result.subject_ = subject_;
      result.notesContentType_ = notesContentType_;
      result.notesContent_ = notesContent_;
      if (incidentsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          incidents_ = java.util.Collections.unmodifiableList(incidents_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.incidents_ = incidents_;
      } else {
        result.incidents_ = incidentsBuilder_.build();
      }
      result.previewOnly_ = previewOnly_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest) {
        return mergeFrom((com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest other) {
      if (other == com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.getDefaultInstance())
        return this;
      if (!other.getParent().isEmpty()) {
        parent_ = other.parent_;
        onChanged();
      }
      if (!other.recipients_.isEmpty()) {
        if (recipients_.isEmpty()) {
          recipients_ = other.recipients_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureRecipientsIsMutable();
          recipients_.addAll(other.recipients_);
        }
        onChanged();
      }
      if (!other.cc_.isEmpty()) {
        if (cc_.isEmpty()) {
          cc_ = other.cc_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureCcIsMutable();
          cc_.addAll(other.cc_);
        }
        onChanged();
      }
      if (!other.getSubject().isEmpty()) {
        subject_ = other.subject_;
        onChanged();
      }
      if (!other.getNotesContentType().isEmpty()) {
        notesContentType_ = other.notesContentType_;
        onChanged();
      }
      if (!other.getNotesContent().isEmpty()) {
        notesContent_ = other.notesContent_;
        onChanged();
      }
      if (incidentsBuilder_ == null) {
        if (!other.incidents_.isEmpty()) {
          if (incidents_.isEmpty()) {
            incidents_ = other.incidents_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureIncidentsIsMutable();
            incidents_.addAll(other.incidents_);
          }
          onChanged();
        }
      } else {
        if (!other.incidents_.isEmpty()) {
          if (incidentsBuilder_.isEmpty()) {
            incidentsBuilder_.dispose();
            incidentsBuilder_ = null;
            incidents_ = other.incidents_;
            bitField0_ = (bitField0_ & ~0x00000040);
            incidentsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                    ? getIncidentsFieldBuilder()
                    : null;
          } else {
            incidentsBuilder_.addAllMessages(other.incidents_);
          }
        }
      }
      if (other.getPreviewOnly() != false) {
        setPreviewOnly(other.getPreviewOnly());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =
            (com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.lang.Object parent_ = "";
    /**
     *
     *
     * <pre>
     * The resource name of the Stackdriver project that the handoff is being sent
     * from. for example, `projects/{project_id}`
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public java.lang.String getParent() {
      java.lang.Object ref = parent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The resource name of the Stackdriver project that the handoff is being sent
     * from. for example, `projects/{project_id}`
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public com.google.protobuf.ByteString getParentBytes() {
      java.lang.Object ref = parent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        parent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The resource name of the Stackdriver project that the handoff is being sent
     * from. for example, `projects/{project_id}`
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public Builder setParent(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      parent_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The resource name of the Stackdriver project that the handoff is being sent
     * from. for example, `projects/{project_id}`
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public Builder clearParent() {

      parent_ = getDefaultInstance().getParent();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The resource name of the Stackdriver project that the handoff is being sent
     * from. for example, `projects/{project_id}`
     * </pre>
     *
     * <code>string parent = 1;</code>
     */
    public Builder setParentBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      parent_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList recipients_ =
        com.google.protobuf.LazyStringArrayList.EMPTY;

    private void ensureRecipientsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        recipients_ = new com.google.protobuf.LazyStringArrayList(recipients_);
        bitField0_ |= 0x00000002;
      }
    }
    /**
     *
     *
     * <pre>
     * Email addresses of the recipients of the handoff, for example,
     * "user&#64;example.com". Must contain at least one entry.
     * </pre>
     *
     * <code>repeated string recipients = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList getRecipientsList() {
      return recipients_.getUnmodifiableView();
    }
    /**
     *
     *
     * <pre>
     * Email addresses of the recipients of the handoff, for example,
     * "user&#64;example.com". Must contain at least one entry.
     * </pre>
     *
     * <code>repeated string recipients = 2;</code>
     */
    public int getRecipientsCount() {
      return recipients_.size();
    }
    /**
     *
     *
     * <pre>
     * Email addresses of the recipients of the handoff, for example,
     * "user&#64;example.com". Must contain at least one entry.
     * </pre>
     *
     * <code>repeated string recipients = 2;</code>
     */
    public java.lang.String getRecipients(int index) {
      return recipients_.get(index);
    }
    /**
     *
     *
     * <pre>
     * Email addresses of the recipients of the handoff, for example,
     * "user&#64;example.com". Must contain at least one entry.
     * </pre>
     *
     * <code>repeated string recipients = 2;</code>
     */
    public com.google.protobuf.ByteString getRecipientsBytes(int index) {
      return recipients_.getByteString(index);
    }
    /**
     *
     *
     * <pre>
     * Email addresses of the recipients of the handoff, for example,
     * "user&#64;example.com". Must contain at least one entry.
     * </pre>
     *
     * <code>repeated string recipients = 2;</code>
     */
    public Builder setRecipients(int index, java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRecipientsIsMutable();
      recipients_.set(index, value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Email addresses of the recipients of the handoff, for example,
     * "user&#64;example.com". Must contain at least one entry.
     * </pre>
     *
     * <code>repeated string recipients = 2;</code>
     */
    public Builder addRecipients(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRecipientsIsMutable();
      recipients_.add(value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Email addresses of the recipients of the handoff, for example,
     * "user&#64;example.com". Must contain at least one entry.
     * </pre>
     *
     * <code>repeated string recipients = 2;</code>
     */
    public Builder addAllRecipients(java.lang.Iterable<java.lang.String> values) {
      ensureRecipientsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(values, recipients_);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Email addresses of the recipients of the handoff, for example,
     * "user&#64;example.com". Must contain at least one entry.
     * </pre>
     *
     * <code>repeated string recipients = 2;</code>
     */
    public Builder clearRecipients() {
      recipients_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Email addresses of the recipients of the handoff, for example,
     * "user&#64;example.com". Must contain at least one entry.
     * </pre>
     *
     * <code>repeated string recipients = 2;</code>
     */
    public Builder addRecipientsBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureRecipientsIsMutable();
      recipients_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList cc_ = com.google.protobuf.LazyStringArrayList.EMPTY;

    private void ensureCcIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        cc_ = new com.google.protobuf.LazyStringArrayList(cc_);
        bitField0_ |= 0x00000004;
      }
    }
    /**
     *
     *
     * <pre>
     * Email addresses that should be CC'd on the handoff. Optional.
     * </pre>
     *
     * <code>repeated string cc = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList getCcList() {
      return cc_.getUnmodifiableView();
    }
    /**
     *
     *
     * <pre>
     * Email addresses that should be CC'd on the handoff. Optional.
     * </pre>
     *
     * <code>repeated string cc = 3;</code>
     */
    public int getCcCount() {
      return cc_.size();
    }
    /**
     *
     *
     * <pre>
     * Email addresses that should be CC'd on the handoff. Optional.
     * </pre>
     *
     * <code>repeated string cc = 3;</code>
     */
    public java.lang.String getCc(int index) {
      return cc_.get(index);
    }
    /**
     *
     *
     * <pre>
     * Email addresses that should be CC'd on the handoff. Optional.
     * </pre>
     *
     * <code>repeated string cc = 3;</code>
     */
    public com.google.protobuf.ByteString getCcBytes(int index) {
      return cc_.getByteString(index);
    }
    /**
     *
     *
     * <pre>
     * Email addresses that should be CC'd on the handoff. Optional.
     * </pre>
     *
     * <code>repeated string cc = 3;</code>
     */
    public Builder setCc(int index, java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCcIsMutable();
      cc_.set(index, value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Email addresses that should be CC'd on the handoff. Optional.
     * </pre>
     *
     * <code>repeated string cc = 3;</code>
     */
    public Builder addCc(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCcIsMutable();
      cc_.add(value);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Email addresses that should be CC'd on the handoff. Optional.
     * </pre>
     *
     * <code>repeated string cc = 3;</code>
     */
    public Builder addAllCc(java.lang.Iterable<java.lang.String> values) {
      ensureCcIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(values, cc_);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Email addresses that should be CC'd on the handoff. Optional.
     * </pre>
     *
     * <code>repeated string cc = 3;</code>
     */
    public Builder clearCc() {
      cc_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Email addresses that should be CC'd on the handoff. Optional.
     * </pre>
     *
     * <code>repeated string cc = 3;</code>
     */
    public Builder addCcBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureCcIsMutable();
      cc_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object subject_ = "";
    /**
     *
     *
     * <pre>
     * The subject of the email. Required.
     * </pre>
     *
     * <code>string subject = 4;</code>
     */
    public java.lang.String getSubject() {
      java.lang.Object ref = subject_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subject_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The subject of the email. Required.
     * </pre>
     *
     * <code>string subject = 4;</code>
     */
    public com.google.protobuf.ByteString getSubjectBytes() {
      java.lang.Object ref = subject_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        subject_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * The subject of the email. Required.
     * </pre>
     *
     * <code>string subject = 4;</code>
     */
    public Builder setSubject(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      subject_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The subject of the email. Required.
     * </pre>
     *
     * <code>string subject = 4;</code>
     */
    public Builder clearSubject() {

      subject_ = getDefaultInstance().getSubject();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The subject of the email. Required.
     * </pre>
     *
     * <code>string subject = 4;</code>
     */
    public Builder setSubjectBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      subject_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object notesContentType_ = "";
    /**
     *
     *
     * <pre>
     * Content type string, for example, 'text/plain' or 'text/html'.
     * </pre>
     *
     * <code>string notes_content_type = 5;</code>
     */
    public java.lang.String getNotesContentType() {
      java.lang.Object ref = notesContentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notesContentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Content type string, for example, 'text/plain' or 'text/html'.
     * </pre>
     *
     * <code>string notes_content_type = 5;</code>
     */
    public com.google.protobuf.ByteString getNotesContentTypeBytes() {
      java.lang.Object ref = notesContentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        notesContentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Content type string, for example, 'text/plain' or 'text/html'.
     * </pre>
     *
     * <code>string notes_content_type = 5;</code>
     */
    public Builder setNotesContentType(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      notesContentType_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Content type string, for example, 'text/plain' or 'text/html'.
     * </pre>
     *
     * <code>string notes_content_type = 5;</code>
     */
    public Builder clearNotesContentType() {

      notesContentType_ = getDefaultInstance().getNotesContentType();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Content type string, for example, 'text/plain' or 'text/html'.
     * </pre>
     *
     * <code>string notes_content_type = 5;</code>
     */
    public Builder setNotesContentTypeBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      notesContentType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object notesContent_ = "";
    /**
     *
     *
     * <pre>
     * Additional notes to be included in the handoff. Optional.
     * </pre>
     *
     * <code>string notes_content = 6;</code>
     */
    public java.lang.String getNotesContent() {
      java.lang.Object ref = notesContent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        notesContent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Additional notes to be included in the handoff. Optional.
     * </pre>
     *
     * <code>string notes_content = 6;</code>
     */
    public com.google.protobuf.ByteString getNotesContentBytes() {
      java.lang.Object ref = notesContent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        notesContent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Additional notes to be included in the handoff. Optional.
     * </pre>
     *
     * <code>string notes_content = 6;</code>
     */
    public Builder setNotesContent(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      notesContent_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Additional notes to be included in the handoff. Optional.
     * </pre>
     *
     * <code>string notes_content = 6;</code>
     */
    public Builder clearNotesContent() {

      notesContent_ = getDefaultInstance().getNotesContent();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Additional notes to be included in the handoff. Optional.
     * </pre>
     *
     * <code>string notes_content = 6;</code>
     */
    public Builder setNotesContentBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      notesContent_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident>
        incidents_ = java.util.Collections.emptyList();

    private void ensureIncidentsIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        incidents_ =
            new java.util.ArrayList<
                com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident>(incidents_);
        bitField0_ |= 0x00000040;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident,
            com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder,
            com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.IncidentOrBuilder>
        incidentsBuilder_;

    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public java.util.List<com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident>
        getIncidentsList() {
      if (incidentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(incidents_);
      } else {
        return incidentsBuilder_.getMessageList();
      }
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public int getIncidentsCount() {
      if (incidentsBuilder_ == null) {
        return incidents_.size();
      } else {
        return incidentsBuilder_.getCount();
      }
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident getIncidents(
        int index) {
      if (incidentsBuilder_ == null) {
        return incidents_.get(index);
      } else {
        return incidentsBuilder_.getMessage(index);
      }
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public Builder setIncidents(
        int index, com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident value) {
      if (incidentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncidentsIsMutable();
        incidents_.set(index, value);
        onChanged();
      } else {
        incidentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public Builder setIncidents(
        int index,
        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder
            builderForValue) {
      if (incidentsBuilder_ == null) {
        ensureIncidentsIsMutable();
        incidents_.set(index, builderForValue.build());
        onChanged();
      } else {
        incidentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public Builder addIncidents(
        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident value) {
      if (incidentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncidentsIsMutable();
        incidents_.add(value);
        onChanged();
      } else {
        incidentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public Builder addIncidents(
        int index, com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident value) {
      if (incidentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureIncidentsIsMutable();
        incidents_.add(index, value);
        onChanged();
      } else {
        incidentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public Builder addIncidents(
        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder
            builderForValue) {
      if (incidentsBuilder_ == null) {
        ensureIncidentsIsMutable();
        incidents_.add(builderForValue.build());
        onChanged();
      } else {
        incidentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public Builder addIncidents(
        int index,
        com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder
            builderForValue) {
      if (incidentsBuilder_ == null) {
        ensureIncidentsIsMutable();
        incidents_.add(index, builderForValue.build());
        onChanged();
      } else {
        incidentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public Builder addAllIncidents(
        java.lang.Iterable<
                ? extends com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident>
            values) {
      if (incidentsBuilder_ == null) {
        ensureIncidentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, incidents_);
        onChanged();
      } else {
        incidentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public Builder clearIncidents() {
      if (incidentsBuilder_ == null) {
        incidents_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        incidentsBuilder_.clear();
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public Builder removeIncidents(int index) {
      if (incidentsBuilder_ == null) {
        ensureIncidentsIsMutable();
        incidents_.remove(index);
        onChanged();
      } else {
        incidentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder
        getIncidentsBuilder(int index) {
      return getIncidentsFieldBuilder().getBuilder(index);
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.IncidentOrBuilder
        getIncidentsOrBuilder(int index) {
      if (incidentsBuilder_ == null) {
        return incidents_.get(index);
      } else {
        return incidentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public java.util.List<
            ? extends com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.IncidentOrBuilder>
        getIncidentsOrBuilderList() {
      if (incidentsBuilder_ != null) {
        return incidentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(incidents_);
      }
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder
        addIncidentsBuilder() {
      return getIncidentsFieldBuilder()
          .addBuilder(
              com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
                  .getDefaultInstance());
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder
        addIncidentsBuilder(int index) {
      return getIncidentsFieldBuilder()
          .addBuilder(
              index,
              com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident
                  .getDefaultInstance());
    }
    /**
     *
     *
     * <pre>
     * The set of incidents that should be included in the handoff. Optional.
     * </pre>
     *
     * <code>repeated .google.cloud.irm.v1alpha2.SendShiftHandoffRequest.Incident incidents = 7;
     * </code>
     */
    public java.util.List<
            com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder>
        getIncidentsBuilderList() {
      return getIncidentsFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident,
            com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder,
            com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.IncidentOrBuilder>
        getIncidentsFieldBuilder() {
      if (incidentsBuilder_ == null) {
        incidentsBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilderV3<
                com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident,
                com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.Incident.Builder,
                com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest.IncidentOrBuilder>(
                incidents_, ((bitField0_ & 0x00000040) != 0), getParentForChildren(), isClean());
        incidents_ = null;
      }
      return incidentsBuilder_;
    }

    private boolean previewOnly_;
    /**
     *
     *
     * <pre>
     * If set to true a ShiftHandoffResponse will be returned but the handoff
     * will not actually be sent.
     * </pre>
     *
     * <code>bool preview_only = 8;</code>
     */
    public boolean getPreviewOnly() {
      return previewOnly_;
    }
    /**
     *
     *
     * <pre>
     * If set to true a ShiftHandoffResponse will be returned but the handoff
     * will not actually be sent.
     * </pre>
     *
     * <code>bool preview_only = 8;</code>
     */
    public Builder setPreviewOnly(boolean value) {

      previewOnly_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * If set to true a ShiftHandoffResponse will be returned but the handoff
     * will not actually be sent.
     * </pre>
     *
     * <code>bool preview_only = 8;</code>
     */
    public Builder clearPreviewOnly() {

      previewOnly_ = false;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.cloud.irm.v1alpha2.SendShiftHandoffRequest)
  }

  // @@protoc_insertion_point(class_scope:google.cloud.irm.v1alpha2.SendShiftHandoffRequest)
  private static final com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest();
  }

  public static com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SendShiftHandoffRequest> PARSER =
      new com.google.protobuf.AbstractParser<SendShiftHandoffRequest>() {
        @java.lang.Override
        public SendShiftHandoffRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SendShiftHandoffRequest(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<SendShiftHandoffRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SendShiftHandoffRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.irm.service.v1alpha2.api.SendShiftHandoffRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
