/*
 * Copyright 2019 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/irm/v1alpha2/incidents.proto

package com.google.irm.service.v1alpha2.api;

public interface SynopsisOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.cloud.irm.v1alpha2.Synopsis)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Content type string, for example, 'text/plain' or 'text/markdown'.
   * </pre>
   *
   * <code>string content_type = 1;</code>
   *
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   *
   *
   * <pre>
   * Content type string, for example, 'text/plain' or 'text/markdown'.
   * </pre>
   *
   * <code>string content_type = 1;</code>
   *
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString getContentTypeBytes();

  /**
   *
   *
   * <pre>
   * Textual content of the synopsis. It can be plain text or markdown as
   * indicated by the content_type.
   * </pre>
   *
   * <code>string content = 2;</code>
   *
   * @return The content.
   */
  java.lang.String getContent();
  /**
   *
   *
   * <pre>
   * Textual content of the synopsis. It can be plain text or markdown as
   * indicated by the content_type.
   * </pre>
   *
   * <code>string content = 2;</code>
   *
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString getContentBytes();

  /**
   *
   *
   * <pre>
   * Last updated timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 3;</code>
   *
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   *
   *
   * <pre>
   * Last updated timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 3;</code>
   *
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   *
   *
   * <pre>
   * Last updated timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp update_time = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();

  /**
   *
   *
   * <pre>
   * Author of the synopsis.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.User author = 4;</code>
   *
   * @return Whether the author field is set.
   */
  boolean hasAuthor();
  /**
   *
   *
   * <pre>
   * Author of the synopsis.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.User author = 4;</code>
   *
   * @return The author.
   */
  com.google.irm.service.v1alpha2.api.User getAuthor();
  /**
   *
   *
   * <pre>
   * Author of the synopsis.
   * </pre>
   *
   * <code>.google.cloud.irm.v1alpha2.User author = 4;</code>
   */
  com.google.irm.service.v1alpha2.api.UserOrBuilder getAuthorOrBuilder();
}
